name: Deployment

on: 
  workflow_dispatch

jobs:
  deployment:
    runs-on: [self-hosted, production]
    environment: production
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Start
        run: dotnet run --no-build --project HVZ.Web