# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Install .NET 7.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0

    - name: Test
      run: dotnet test --no-build --verbosity normal
